Fix AST calculation does not work when extrapolated antibiotics
The calculation does not work properly for resistance test when
at least one of the antibiotics have extrapolated. The following
error happens silently because senaite.core calculate func does
not inform about the error.

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.app.listing.view, line 248, in __call__
  Module senaite.app.listing.ajax, line 113, in handle_subpath
  Module senaite.app.listing.decorators, line 63, in wrapper
  Module senaite.app.listing.decorators, line 50, in wrapper
  Module senaite.app.listing.decorators, line 100, in wrapper
  Module senaite.app.listing.ajax, line 647, in ajax_set_fields
  Module senaite.app.listing.ajax, line 432, in set_field
  Module senaite.core.datamanagers.analysis, line 112, in set
  Module senaite.ast.datamanagers, line 38, in recalculate_results
  Module senaite.core.datamanagers.analysis, line 130, in recalculate_results
  Module bika.lims.content.abstractanalysis, line 613, in calculateResult
TypeError: argument of type 'NoneType' is not iterable
```